# Generated by Django 6.0.1 on 2026-01-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_oferta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='medida_valor',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Ej: 1.5, 500, etc.', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.CharField(choices=[('L', 'Litros'), ('KG', 'Kilogramos'), ('UN', 'Unidades')], default='UN', max_length=2),
        ),
    ]
