# Generated by Django 6.0.1 on 2026-01-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_disponible_producto_es_oferta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='es_oferta',
        ),
        migrations.AddField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(default=False, verbose_name='¿Está en Oferta?'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponible',
            field=models.BooleanField(default=True, verbose_name='¿Mostrar en Web?'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='medida_valor',
            field=models.DecimalField(decimal_places=2, help_text='Ej: 1.5, 5, 500', max_digits=5),
        ),
    ]
