# Generated by Django 6.0.1 on 2026-02-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_remove_producto_es_oferta_producto_oferta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('detalle_envio', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('productos_data', models.JSONField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('entregado', models.BooleanField(default=False, verbose_name='¿Ya se entregó y cobró?')),
            ],
        ),
    ]
